sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "9"
before_install: .travis/before_install.sh
deploy:
  provider: script
  skip_cleanup: true
  script: .travis/deploy.sh
script: yarn bootstrap && yarn build && yarn test:ci
git:
  depth: 1
