sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "9"
before_install: .travis/before_install.sh
after_success: .travis/after_success.sh
script: yarn bootstrap && yarn build && yarn test:ci
git:
  depth: 1
