sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "9"
after_success: .travis/after_success.sh
script: yarn bootstrap && yarn build && yarn test
git:
  depth: 1
